language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS --no-interaction
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then composer require jsq/iron-php; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
